[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.143.0"

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

[template.environment]
  HUGO_ENV = "production" 